package tests;

import helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;


import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class SkbBankTests extends TestBase {
    @Test
    @DisplayName("skbbank test")
    void generatedTest() {
        step("Открыть https://skbbank.ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("Перейти на вкладку \"Вклады\"", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://skbbank.ru/'", () ->
            open("https://skbbank.ru/"));

        step("Page title should have text 'Частным клиентам: кредит наличными, интернет банк, вклады, кредитные карты с cash-back, переводы с карты на карту | СКБ-Банк'", () -> {
            String expectedTitle = "Частным клиентам: кредит наличными, интернет банк, вклады, кредитные карты с cash-back, переводы с карты на карту | СКБ-Банк";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://skbbank.ru/'", () ->
            open("https://skbbank.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}